export enum ResourceAssetStrings {
    assetTypeDescription = "Consistent experiences across Azure enable users to leverage a few well-known and researched design patterns throughout Azure.",
    assetTypeKeywords = "UX UI design patterns sample extension ibiza consistency",
    assetTypeLink1Title = "Get consistent",
    assetTypeLink2Title = "Learn more",
    assetTypeNamesResourceLowerPlural = "my resources",
    assetTypeNamesResourceLowerSingular = "my resource",
    assetTypeNamesResourcePlural = "My Resources",
    assetTypeNamesResourceSingular = "My Resource",
    delete = "Delete",
    deleteConfirmation = "Are you sure you want to delete this resource?",
    deleteResourcesTitle = "Delete resource(s)",
    item1 = "Item1",
    item1Keywords = "one keyword1",
    item2 = "Item2",
    item2Keywords = "two keyword2",
    menuGroup1 = "Resource-specific group",
    overview = "Overview",
    overviewKeywords = "Summary Home",
    resourceSettingMenuItem1 = "Important setting",
    settings = "Settings",
    yes = "yes",
}
